### ISSUE TITLE
Nested form objects during validation have the wrong ActiveModel::Name

### ISSUE THREAD

**Issue by mcmire** [trailblazer/reform-rails#36]
Say you have two forms, and one is nested in relation to the other, and you have validations on both forms:

``` ruby
class Order < ApplicationRecord
  has_many :items, class_name: OrderItem
end

class OrderItem < ApplicationRecord
end

class OrderForm < Reform::Form
  property :recipient_name
  collection :items, form: OrderItemForm

  validates :recipient_name, presence: true
end

class OrderItemForm < Reform::Form
  validates :product_id, presence: true    # links to some fictitious Product, whatever
end
```

Also (for the sake of completion) say you have a generic setup like this in your controller:

``` ruby
class OrdersController < ApplicationController
  def create
    order_form = OrderForm.new(Order.new)
    
    if order_form.validate(params[:order])
      # ...
    else
      # ...
    end
  end
end
```

Now let's say that you've want to provide custom translations for these validations. You can do this easily for the parent form:

``` yaml
en:
  activemodel:
    errors:
      models:
        order:
          attributes:
            recipient_name:
              blank: "Please provide a name for the recipient."
```

But if you want to provide translations for the child form...

``` yaml
en:
  activemodel:
    errors:
      models:
        order_item:
          attributes:
            product_id:
              blank: "Please choose a product."
```

...this won't work. It seems that if you ask the child form instance (or wrapped instance, perhaps) what its model_name is, you get something interesting:

```
> order.items[0].lookup_ancestors[0].model_name
=> #<ActiveModel::Name:0x007fe1c671d888
 @collection="items",
 @element="item",
 @human="Item",
 @i18n_key=:item,
 @klass=OrderItemForm,
 @name="Item",
 @param_key="item",
 @plural="items",
 @route_key="items",
 @singular="item",
 @singular_route_key="item">
```

What this means is, I actually need to say this in my locale file:

``` yaml
en:
  activemodel:
    errors:
      models:
        item:
          attributes:
            product_id:
              blank: "Please choose a product."
```

I've been hunting around in Reform and I stumbled upon these lines: https://github.com/trailblazer/reform-rails/blob/master/lib/reform/form/active_model.rb#L34

Could this have anything to do with it?
