### ISSUE TITLE
Using errors.add(:key, 'some text') doesn't translate :key in rails 5

### ISSUE THREAD

**Issue by karlingen** [trailblazer/reform-rails#56]
Attribute names are no longer translated. I'm not sure where the problem is, wether it is with `reform-rails`, `i18n` and/or `rails`. Maybe I'm calling the error messages in a wrong way. 

Example: 

```ruby
module Documents::Contract
  class Create < Reform::Form

    property :name
    validate :file_has_valid_format?

    private

    def file_has_valid_format?
      errors.add(:name, I18n.t('validation.messages.error.file_type_upload_invalid'))
    end
  end
end

```

In rails 4 `:name` was translated to whatever I had defined in `activerecord.en.yml`:

```yml
en:
  activerecord:
    attributes:
      document:
        name: "The X File"
        description: "Descriptionzz"
```

I'm getting the error message like this: 
```ruby
@form.errors.full_messages.join(". ")
```

Gemfile.lock: 
```
trailblazer-rails (1.0.2)
      reform-rails (>= 0.1.4, < 0.2.0)
      trailblazer (>= 2.0.0, < 2.1.0)
      trailblazer-loader (>= 0.1.0)
```
